language: python

python:
  - "3.4"
# command to install dependencies
install:
  - pip install -r requirements-dev.txt --allow-all-external
# command to run tests
script:
  - flake8
  - py.test --cov openjudge --cov-report html

after_success:
  - coveralls
